/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

const FILE_IS_TOO_BIG = 'FILE_IS_TOO_BIG';
const FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED';
const SVG_CONTAINS_ACTIVE_CONTENT = 'SVG_CONTAINS_ACTIVE_CONTENT';
const NOT_ENOUGH_STORAGE = 'NOT_ENOUGH_STORAGE';
const EMPTY_TRASH = 'EMPTY_TRASH';
const SOURCE_CARD_NOT_COPYABLE = 'SOURCE_CARD_NOT_COPYABLE';
const SOURCE_CARD_NOT_MOVABLE = 'SOURCE_CARD_NOT_MOVABLE';
const HIPPO_SYNC_FAILED = 'HIPPO_SYNC_FAILED';
const HIPPO_IMPORT_INCOMPLETE = 'HIPPO_IMPORT_INCOMPLETE';

export default {
  FILE_IS_TOO_BIG,
  FILE_TYPE_NOT_ALLOWED,
  SVG_CONTAINS_ACTIVE_CONTENT,
  NOT_ENOUGH_STORAGE,
  EMPTY_TRASH,
  SOURCE_CARD_NOT_COPYABLE,
  SOURCE_CARD_NOT_MOVABLE,
  HIPPO_SYNC_FAILED,
  HIPPO_IMPORT_INCOMPLETE,
};
